import type { Style2D } from "@/lib/generate2DFrames";

/**
 * The full preset gallery. Each preset carries not just its card presentation
 * (gradient / accent) but the animation `style` and `colors` triple that the
 * canvas renderer needs, so every preset generates a distinct site.
 */
export interface Preset {
  name: string;
  category: string;
  description: string;
  tags: string[];
  gradient: string;
  accent: string;
  prompt: string;
  style: Style2D;
  colors: [string, string, string];
}

export const PRESETS: Preset[] = [
  // ── SaaS ───────────────────────────────────────────────────────────────────
  {
    name: "OrbitCRM",
    category: "SaaS",
    description: "Dark SaaS hero with floating UI elements",
    tags: ["Dark", "Tech", "Dashboard"],
    gradient: "from-violet-800 via-purple-900 to-violet-950",
    accent: "#a78bfa",
    prompt: "Cinematic flythrough of a dark futuristic digital dashboard. Glowing UI panels float in dark space. Purple and blue neon accents. Depth of field blur.",
    style: "gradient",
    colors: ["#7c3aed", "#2563eb", "#0f172a"],
  },
  {
    name: "SyncBase",
    category: "SaaS",
    description: "Productivity tool with clean minimal scroll",
    tags: ["Minimal", "Teal", "Productivity"],
    gradient: "from-emerald-800 via-teal-900 to-emerald-950",
    accent: "#34d399",
    prompt: "Abstract flowing data streams in deep space. Green and teal particle effects moving through darkness. Clean, technical, modern.",
    style: "particles",
    colors: ["#10b981", "#14b8a6", "#021410"],
  },
  {
    name: "PulseMetrics",
    category: "SaaS",
    description: "Real-time analytics platform with live data hero",
    tags: ["Analytics", "Cyan", "Live"],
    gradient: "from-cyan-700 via-sky-800 to-cyan-900",
    accent: "#67e8f9",
    prompt: "Abstract data visualization with glowing line charts and pulse waves in deep teal space. Real-time energy. Clean technical aesthetic.",
    style: "wave",
    colors: ["#06b6d4", "#0284c7", "#04141c"],
  },
  {
    name: "FlowDeploy",
    category: "SaaS",
    description: "CI/CD pipeline tool with kinetic flow aesthetic",
    tags: ["DevOps", "Green", "Pipeline"],
    gradient: "from-green-700 via-emerald-800 to-green-900",
    accent: "#86efac",
    prompt: "Abstract network of glowing green nodes and connections flowing like a river of light. Pipeline metaphor. Dark background, emerald glow.",
    style: "wave",
    colors: ["#22c55e", "#10b981", "#02140a"],
  },
  {
    name: "NexusHQ",
    category: "SaaS",
    description: "All-in-one workspace with warm collaborative energy",
    tags: ["Workspace", "Amber", "Bold"],
    gradient: "from-orange-700 via-amber-800 to-orange-950",
    accent: "#fb923c",
    prompt: "Abstract interconnected hexagonal grid in warm amber tones. Orbiting dots suggest collaboration and connectivity. Warm cinematic grade.",
    style: "geometric",
    colors: ["#f97316", "#d97706", "#1a0d02"],
  },
  {
    name: "VaultDB",
    category: "SaaS",
    description: "Database-as-a-service with secure fortress branding",
    tags: ["Database", "Indigo", "Secure"],
    gradient: "from-indigo-700 via-blue-800 to-indigo-950",
    accent: "#818cf8",
    prompt: "Abstract glowing data vault — layers of hexagonal shields illuminated in deep indigo. Secure, architectural, cinematic.",
    style: "geometric",
    colors: ["#4f46e5", "#1d4ed8", "#05061a"],
  },

  // ── Agency ─────────────────────────────────────────────────────────────────
  {
    name: "Meridian",
    category: "Agency",
    description: "Premium agency portfolio with bold editorial scroll",
    tags: ["Dark", "Minimal", "Editorial"],
    gradient: "from-slate-700 via-slate-800 to-slate-900",
    accent: "#e2e8f0",
    prompt: "A slow cinematic pan through a modernist architecture interior. Concrete and glass. Dark, premium, editorial feel. Shallow depth of field.",
    style: "geometric",
    colors: ["#94a3b8", "#475569", "#0b0f17"],
  },
  {
    name: "LuminaStudio",
    category: "Agency",
    description: "Creative studio with vivid bold photography",
    tags: ["Creative", "Bold", "Color"],
    gradient: "from-rose-700 via-pink-800 to-rose-900",
    accent: "#fb7185",
    prompt: "Abstract explosion of vibrant color pigments in slow motion. Paint in water. Cinematic macro. Bold, artistic, vivid.",
    style: "gradient",
    colors: ["#f43f5e", "#db2777", "#1a0410"],
  },
  {
    name: "BlackAtlas",
    category: "Agency",
    description: "Global branding agency with monochrome elegance",
    tags: ["Monochrome", "Premium", "Global"],
    gradient: "from-gray-600 via-gray-700 to-gray-900",
    accent: "#9ca3af",
    prompt: "Slow pan over a black marble surface with subtle white veining. Premium material. Studio lighting. Monochrome luxury.",
    style: "wave",
    colors: ["#9ca3af", "#4b5563", "#0a0a0c"],
  },
  {
    name: "Chromatic",
    category: "Agency",
    description: "Design-led agency with gradient-first visual identity",
    tags: ["Gradient", "Vibrant", "Design"],
    gradient: "from-violet-700 via-fuchsia-800 to-violet-900",
    accent: "#d8b4fe",
    prompt: "Slow morphing abstract color field — violet bleeds into fuchsia into deep purple. Liquid light. Cinematic color grade.",
    style: "gradient",
    colors: ["#8b5cf6", "#c026d3", "#12031a"],
  },

  // ── E-commerce ─────────────────────────────────────────────────────────────
  {
    name: "Shopnest",
    category: "E-commerce",
    description: "Luxury e-commerce with dramatic product reveal scroll",
    tags: ["Luxury", "Gold", "Product"],
    gradient: "from-amber-800 via-yellow-900 to-amber-950",
    accent: "#f59e0b",
    prompt: "Ultra slow macro product shot. Luxury leather texture in dramatic studio lighting. Black background, golden rim light. Commercial photography.",
    style: "gradient",
    colors: ["#f59e0b", "#ca8a04", "#1a1002"],
  },
  {
    name: "AuraBeauty",
    category: "E-commerce",
    description: "Premium beauty brand with soft cinematic glow",
    tags: ["Beauty", "Soft", "Pink"],
    gradient: "from-pink-700 via-rose-800 to-pink-900",
    accent: "#f9a8d4",
    prompt: "Macro shot of soft pink rose petals with water droplets in dramatic studio lighting. Beauty brand aesthetic. Pastel luxury.",
    style: "wave",
    colors: ["#ec4899", "#f43f5e", "#1a0510"],
  },
  {
    name: "NordGoods",
    category: "E-commerce",
    description: "Scandinavian minimalist goods with clean scroll",
    tags: ["Minimal", "Nordic", "Clean"],
    gradient: "from-slate-500 via-slate-700 to-slate-800",
    accent: "#cbd5e1",
    prompt: "Clean product photography on pure white surface. Minimal Scandinavian home goods. Perfect studio lighting. Stark, beautiful, editorial.",
    style: "geometric",
    colors: ["#cbd5e1", "#64748b", "#0d1117"],
  },
  {
    name: "VaultKicks",
    category: "E-commerce",
    description: "Sneaker marketplace with street-culture energy",
    tags: ["Street", "Bold", "Dynamic"],
    gradient: "from-orange-800 via-red-900 to-neutral-950",
    accent: "#fdba74",
    prompt: "Cinematic slow-motion sneaker drop in warm studio light. Orange and amber tones. Dramatic product hero. Street culture energy.",
    style: "gradient",
    colors: ["#f97316", "#dc2626", "#190602"],
  },
  {
    name: "JewelBox",
    category: "E-commerce",
    description: "Fine jewellery store with faceted light effects",
    tags: ["Jewellery", "Luxury", "Sparkle"],
    gradient: "from-yellow-700 via-amber-800 to-yellow-950",
    accent: "#fcd34d",
    prompt: "Ultra macro shot of a diamond facet refracting rainbow light in slow motion. Dark background. Light splits into spectral rays. Luxury.",
    style: "geometric",
    colors: ["#eab308", "#d97706", "#1a1402"],
  },

  // ── Mobile App ─────────────────────────────────────────────────────────────
  {
    name: "TripVault",
    category: "Mobile App",
    description: "Travel app showcase with destination flythrough",
    tags: ["Travel", "Sky Blue", "Immersive"],
    gradient: "from-sky-700 via-blue-800 to-indigo-900",
    accent: "#38bdf8",
    prompt: "Aerial cinematic flyover of turquoise tropical coastline at golden hour. Drone shot, warm colors, crystal water, lush green islands.",
    style: "gradient",
    colors: ["#0284c7", "#0891b2", "#020c1a"],
  },
  {
    name: "DreamTrack",
    category: "Mobile App",
    description: "Sleep & wellness tracker with dreamy ambient visuals",
    tags: ["Wellness", "Purple", "Calm"],
    gradient: "from-purple-700 via-violet-800 to-purple-950",
    accent: "#c4b5fd",
    prompt: "Slow time-lapse of bioluminescent jellyfish drifting in deep purple ocean. Dreamy, calm, otherworldly. Ultra cinematic.",
    style: "wave",
    colors: ["#9333ea", "#7c3aed", "#0d0418"],
  },
  {
    name: "SwiftPay",
    category: "Mobile App",
    description: "Instant payment app with electric speed branding",
    tags: ["Payments", "Green", "Fast"],
    gradient: "from-lime-700 via-green-800 to-lime-900",
    accent: "#bef264",
    prompt: "Abstract electric current flowing through neon green circuit pathways in dark space. Speed and precision. Fintech energy.",
    style: "geometric",
    colors: ["#84cc16", "#16a34a", "#0a1402"],
  },
  {
    name: "FitPulse",
    category: "Mobile App",
    description: "Fitness tracking app with raw kinetic energy",
    tags: ["Fitness", "Red", "Energy"],
    gradient: "from-red-700 via-orange-800 to-red-950",
    accent: "#fca5a5",
    prompt: "Slow motion cinematic shot of fire embers and sparks flying upward against black. Intense energy, ambition, motion blur.",
    style: "particles",
    colors: ["#dc2626", "#ea580c", "#190402"],
  },

  // ── Startup ────────────────────────────────────────────────────────────────
  {
    name: "Mindloop",
    category: "Startup",
    description: "Newsletter platform with liquid-glass minimal UI",
    tags: ["Glass", "Mono", "Content"],
    gradient: "from-neutral-700 via-zinc-800 to-neutral-900",
    accent: "#a3a3a3",
    prompt: "Slow motion liquid glass surface with subtle refractions. Monochrome. Ultra minimal. Premium material render. Studio lighting.",
    style: "wave",
    colors: ["#a3a3a3", "#52525b", "#0c0c0e"],
  },
  {
    name: "Launchpad",
    category: "Startup",
    description: "Bold launch page with rocket energy and bright accents",
    tags: ["Launch", "Yellow", "Bold"],
    gradient: "from-amber-600 via-orange-800 to-amber-950",
    accent: "#fde047",
    prompt: "Cinematic slow-motion rocket launch through amber clouds at dusk. Light bursts through cloud formations. Epic scale. Ignition energy.",
    style: "gradient",
    colors: ["#facc15", "#f59e0b", "#1a1402"],
  },
  {
    name: "Zephyr",
    category: "Startup",
    description: "Web3 protocol with flowing abstract teal aesthetic",
    tags: ["Web3", "Teal", "Flow"],
    gradient: "from-teal-700 via-cyan-800 to-teal-950",
    accent: "#5eead4",
    prompt: "Abstract flowing teal aurora-like light ribbons moving in deep space. Ethereal, smooth, blockchain metaphor. Ultra cinematic.",
    style: "wave",
    colors: ["#14b8a6", "#0891b2", "#021416"],
  },
  {
    name: "Beacon",
    category: "Startup",
    description: "Media and newsletter brand with editorial warmth",
    tags: ["Media", "Indigo", "Editorial"],
    gradient: "from-indigo-800 via-blue-900 to-slate-950",
    accent: "#a5b4fc",
    prompt: "Soft focused light bokeh through glass. Indigo and blue. Editorial newspaper aesthetic. Premium print magazine feel.",
    style: "particles",
    colors: ["#6366f1", "#2563eb", "#060818"],
  },
  {
    name: "GreenShift",
    category: "Startup",
    description: "Climate tech startup with organic earthy visuals",
    tags: ["Climate", "Green", "Organic"],
    gradient: "from-green-700 via-lime-800 to-green-950",
    accent: "#86efac",
    prompt: "Time-lapse of lush green forest canopy from drone. Morning light through leaves. Organic, alive, hopeful. Climate-forward.",
    style: "wave",
    colors: ["#059669", "#0d9488", "#021a10"],
  },

  // ── Developer Tool ──────────────────────────────────────────────────────────
  {
    name: "StackForge",
    category: "Developer Tool",
    description: "Dev tool landing with cinematic code-depth aesthetic",
    tags: ["Code", "Cyan", "Dark"],
    gradient: "from-zinc-700 via-zinc-800 to-zinc-900",
    accent: "#22d3ee",
    prompt: "Cinematic zoom through lines of glowing code on dark screens. Matrix-like but premium. Cyan and white light trails. Depth of field.",
    style: "particles",
    colors: ["#22d3ee", "#52525b", "#08090c"],
  },
  {
    name: "AutoMachines",
    category: "Developer Tool",
    description: "Automation platform with geometric precision",
    tags: ["Automation", "Stone", "Geometric"],
    gradient: "from-stone-700 via-neutral-800 to-stone-900",
    accent: "#d4d4d4",
    prompt: "Cinematic shot of robotic assembly arms in dark factory. Sparks flying, precision motion. Industrial but premium. Slow motion.",
    style: "geometric",
    colors: ["#d4d4d4", "#78716c", "#0c0b0a"],
  },
  {
    name: "CodePilot",
    category: "Developer Tool",
    description: "AI coding assistant with neural-network hero",
    tags: ["AI", "Emerald", "Code"],
    gradient: "from-emerald-700 via-green-800 to-emerald-950",
    accent: "#6ee7b7",
    prompt: "Glowing green circuit board traces in macro. Deep focus. Neural network of connections. Premium developer aesthetic.",
    style: "geometric",
    colors: ["#10b981", "#16a34a", "#02140c"],
  },
  {
    name: "Terminus",
    category: "Developer Tool",
    description: "Terminal and CLI tool with retro-modern identity",
    tags: ["Terminal", "Green", "Retro"],
    gradient: "from-green-800 via-emerald-900 to-green-950",
    accent: "#4ade80",
    prompt: "Green monochrome terminal text scrolling rapidly on black screen. CRT glow effect. Retro-computing meets modern precision.",
    style: "particles",
    colors: ["#22c55e", "#059669", "#01120a"],
  },

  // ── AI Platform ─────────────────────────────────────────────────────────────
  {
    name: "VisionForge",
    category: "AI Platform",
    description: "AI platform with cinematic neural network visuals",
    tags: ["AI", "Fuchsia", "Neural"],
    gradient: "from-fuchsia-800 via-pink-900 to-fuchsia-950",
    accent: "#e879f9",
    prompt: "Abstract neural network visualization. Glowing nodes and connections in deep purple space. Data flowing between points. Ultra cinematic.",
    style: "particles",
    colors: ["#d946ef", "#be185d", "#170318"],
  },
  {
    name: "Power AI",
    category: "AI Platform",
    description: "Full-screen dark hero with electric AI energy",
    tags: ["AI", "Indigo", "Bold"],
    gradient: "from-indigo-800 via-violet-900 to-indigo-950",
    accent: "#818cf8",
    prompt: "Abstract AI energy field. Electric indigo and violet light bursts in dark space. Powerful, dynamic, cinematic. Slow motion.",
    style: "gradient",
    colors: ["#4f46e5", "#7c3aed", "#08061a"],
  },
  {
    name: "Synthex",
    category: "AI Platform",
    description: "Generative AI platform with morphing abstract visuals",
    tags: ["Generative", "Purple", "Morph"],
    gradient: "from-violet-700 via-purple-800 to-violet-950",
    accent: "#c084fc",
    prompt: "Abstract morphing geometric shapes in violet. Smooth AI-generated transitions between forms. Generative art aesthetic.",
    style: "geometric",
    colors: ["#8b5cf6", "#9333ea", "#0f0418"],
  },
  {
    name: "NeuralPath",
    category: "AI Platform",
    description: "AI research lab with deep science aesthetic",
    tags: ["Research", "Blue", "Science"],
    gradient: "from-blue-700 via-cyan-800 to-blue-950",
    accent: "#7dd3fc",
    prompt: "3D brain scan visualization with glowing cyan pathways. Medical imaging aesthetic. Data moving through neural pathways.",
    style: "particles",
    colors: ["#2563eb", "#0891b2", "#02101c"],
  },
  {
    name: "Luminary",
    category: "AI Platform",
    description: "AI creative suite with prismatic light effects",
    tags: ["Creative", "Amber", "Prismatic"],
    gradient: "from-amber-700 via-orange-800 to-amber-950",
    accent: "#fbbf24",
    prompt: "Slow motion prism splitting white light into rainbow spectrum. Crystal clear optics. AI creativity metaphor. Cinematic light study.",
    style: "geometric",
    colors: ["#f59e0b", "#ea580c", "#1a0c02"],
  },

  // ── Fintech ─────────────────────────────────────────────────────────────────
  {
    name: "Halo",
    category: "Fintech",
    description: "Stablecoin platform with premium liquid metal feel",
    tags: ["Finance", "Blue", "Premium"],
    gradient: "from-blue-800 via-indigo-900 to-blue-950",
    accent: "#60a5fa",
    prompt: "Abstract liquid metal surface with ripples. Futuristic financial data overlays. Dark blue, silver, premium. Cinematic macro shot.",
    style: "wave",
    colors: ["#3b82f6", "#4338ca", "#040a1a"],
  },
  {
    name: "GoldStack",
    category: "Fintech",
    description: "Investment platform with wealth and gold branding",
    tags: ["Investment", "Gold", "Wealth"],
    gradient: "from-yellow-600 via-yellow-800 to-stone-950",
    accent: "#fcd34d",
    prompt: "Cinematic slow-motion pour of liquid gold. Rich amber tones. Studio macro photography. Investment and wealth aesthetic.",
    style: "wave",
    colors: ["#eab308", "#b45309", "#1a1002"],
  },
  {
    name: "CipherBank",
    category: "Fintech",
    description: "Crypto bank with digital security aesthetics",
    tags: ["Crypto", "Cyan", "Secure"],
    gradient: "from-cyan-700 via-sky-800 to-cyan-950",
    accent: "#38bdf8",
    prompt: "Abstract blockchain data flowing through secure tunnels of light. Cyan and electric blue. Cryptographic security visualized.",
    style: "particles",
    colors: ["#22d3ee", "#0ea5e9", "#021016"],
  },

  // ── Logistics ───────────────────────────────────────────────────────────────
  {
    name: "Targo",
    category: "Logistics",
    description: "Transport & logistics with bold red branding",
    tags: ["Transport", "Red", "Bold"],
    gradient: "from-red-800 via-rose-900 to-red-950",
    accent: "#f87171",
    prompt: "Time-lapse of cargo ships and trucks moving at dusk. Bold industrial aesthetic. Red sky, motion blur, cinematic grade.",
    style: "gradient",
    colors: ["#dc2626", "#be123c", "#190309"],
  },
  {
    name: "SwiftRoute",
    category: "Logistics",
    description: "Last-mile delivery startup with fast urban energy",
    tags: ["Delivery", "Orange", "Urban"],
    gradient: "from-slate-800 via-cyan-900 to-slate-950",
    accent: "#fb923c",
    prompt: "Time-lapse of city street at night — vehicle light trails streaking past. Urban logistics energy. Fast, electric, dynamic.",
    style: "particles",
    colors: ["#ea580c", "#f59e0b", "#170a02"],
  },

  // ── Healthcare ──────────────────────────────────────────────────────────────
  {
    name: "MediFlow",
    category: "Healthcare",
    description: "Medical practice platform with calm clinical teal",
    tags: ["Medical", "Teal", "Clinical"],
    gradient: "from-teal-700 via-emerald-800 to-teal-950",
    accent: "#99f6e4",
    prompt: "Macro shot of water droplets on a clean teal surface. Clinical precision meets warmth. Healthcare digital platform aesthetic.",
    style: "wave",
    colors: ["#0d9488", "#059669", "#02120f"],
  },
  {
    name: "Vitara",
    category: "Healthcare",
    description: "Mental health app with warm gentle visuals",
    tags: ["Mental Health", "Rose", "Gentle"],
    gradient: "from-rose-700 via-pink-800 to-rose-950",
    accent: "#fda4af",
    prompt: "Soft focus shot of cherry blossoms falling in slow motion. Warm pink light. Gentle, healing, mindful aesthetic.",
    style: "particles",
    colors: ["#e11d48", "#ec4899", "#180410"],
  },
  {
    name: "PureGen",
    category: "Healthcare",
    description: "Biotech firm with precision science branding",
    tags: ["Biotech", "Sky", "Precision"],
    gradient: "from-sky-700 via-blue-800 to-sky-950",
    accent: "#7dd3fc",
    prompt: "Abstract DNA helix rendered in glowing sky blue. Rotating slowly in dark space. Biotech precision. Scientific elegance.",
    style: "wave",
    colors: ["#0ea5e9", "#2563eb", "#020a18"],
  },

  // ── Education ───────────────────────────────────────────────────────────────
  {
    name: "LearnSphere",
    category: "Education",
    description: "Online learning platform with cosmic curiosity visuals",
    tags: ["Learning", "Blue", "Cosmic"],
    gradient: "from-blue-700 via-indigo-800 to-blue-950",
    accent: "#93c5fd",
    prompt: "Cinematic flythrough of a galaxy nebula. Stars and cosmic dust in deep blue and violet. Curiosity and exploration metaphor.",
    style: "particles",
    colors: ["#3b82f6", "#4f46e5", "#03071a"],
  },
  {
    name: "MindCraft",
    category: "Education",
    description: "Kids coding platform with playful bright energy",
    tags: ["Kids", "Yellow", "Playful"],
    gradient: "from-yellow-600 via-orange-700 to-yellow-900",
    accent: "#fde047",
    prompt: "Abstract colorful geometric shapes bouncing in a bright playful space. Primary colors. Playful energy. Child-friendly vibrancy.",
    style: "geometric",
    colors: ["#facc15", "#ea580c", "#1a0f02"],
  },

  // ── Gaming ──────────────────────────────────────────────────────────────────
  {
    name: "NightRealm",
    category: "Gaming",
    description: "Dark fantasy RPG with epic cinematic atmosphere",
    tags: ["Fantasy", "Dark", "Epic"],
    gradient: "from-purple-800 via-indigo-900 to-purple-950",
    accent: "#818cf8",
    prompt: "Cinematic pan through a dark fantasy castle on a stormy night. Lightning illuminates gothic spires. Purple and dark blue sky.",
    style: "particles",
    colors: ["#6d28d9", "#1e1b4b", "#030014"],
  },
  {
    name: "Nebula",
    category: "Gaming",
    description: "Space exploration game with breathtaking cosmos",
    tags: ["Space", "Cosmic", "Blue"],
    gradient: "from-blue-800 via-indigo-900 to-slate-950",
    accent: "#60a5fa",
    prompt: "Cinematic journey through a blue and violet nebula. Star formations and gas clouds. Epic space exploration. IMAX quality.",
    style: "particles",
    colors: ["#2563eb", "#4338ca", "#020617"],
  },
  {
    name: "PixelForge",
    category: "Gaming",
    description: "Indie game studio with vibrant creative energy",
    tags: ["Indie", "Fuchsia", "Creative"],
    gradient: "from-fuchsia-700 via-purple-800 to-fuchsia-950",
    accent: "#f0abfc",
    prompt: "Abstract pixel art exploding into 3D geometric shapes. Fuchsia and purple. Game world materializing from code. Creative energy.",
    style: "geometric",
    colors: ["#c026d3", "#9333ea", "#150318"],
  },

  // ── Real Estate ──────────────────────────────────────────────────────────────
  {
    name: "EstateLux",
    category: "Real Estate",
    description: "Luxury property marketplace with aspirational visuals",
    tags: ["Luxury", "Amber", "Premium"],
    gradient: "from-amber-700 via-yellow-800 to-amber-950",
    accent: "#fbbf24",
    prompt: "Aerial drone shot of a luxury villa at golden hour. Pool glinting, palm trees, warm amber sky. Premium real estate aesthetic.",
    style: "gradient",
    colors: ["#f59e0b", "#ca8a04", "#1a1102"],
  },
  {
    name: "UrbanNest",
    category: "Real Estate",
    description: "City apartment finder with modern architectural feel",
    tags: ["Urban", "Slate", "Modern"],
    gradient: "from-slate-600 via-blue-800 to-slate-900",
    accent: "#94a3b8",
    prompt: "Time-lapse of city skyline at dusk — lights turning on one by one. Glass towers reflecting amber sunset. Modern urban living.",
    style: "geometric",
    colors: ["#94a3b8", "#1d4ed8", "#080d16"],
  },

  // ── Restaurant ───────────────────────────────────────────────────────────────
  {
    name: "Ember",
    category: "Restaurant",
    description: "Upscale steakhouse with live fire branding",
    tags: ["Fire", "Orange", "Premium"],
    gradient: "from-orange-700 via-red-800 to-orange-950",
    accent: "#fb923c",
    prompt: "Cinematic slow motion close-up of glowing ember coals. Cooking fire. Deep orange and red. Premium steakhouse atmosphere.",
    style: "particles",
    colors: ["#ea580c", "#b91c1c", "#1a0500"],
  },
  {
    name: "SaffronGarden",
    category: "Restaurant",
    description: "Premium Indian restaurant with rich spice palette",
    tags: ["Indian", "Gold", "Warm"],
    gradient: "from-yellow-600 via-orange-700 to-amber-900",
    accent: "#fbbf24",
    prompt: "Macro shot of vibrant saffron and turmeric spices in warm studio light. Rich golden and orange tones. Aromatic premium dining.",
    style: "gradient",
    colors: ["#eab308", "#f97316", "#1a0e02"],
  },
  {
    name: "FrostBrew",
    category: "Restaurant",
    description: "Craft beer brand with cool refreshing identity",
    tags: ["Beer", "Blue", "Cool"],
    gradient: "from-sky-700 via-blue-800 to-indigo-950",
    accent: "#7dd3fc",
    prompt: "Macro shot of cold beer glass with ice crystals forming. Water droplets on frosted glass. Cool blue light. Refreshing energy.",
    style: "geometric",
    colors: ["#38bdf8", "#3b82f6", "#020818"],
  },

  // ── Creative ─────────────────────────────────────────────────────────────────
  {
    name: "LensCraft",
    category: "Creative",
    description: "Photography portfolio with editorial film elegance",
    tags: ["Photography", "Mono", "Film"],
    gradient: "from-gray-600 via-slate-700 to-gray-900",
    accent: "#94a3b8",
    prompt: "Slow pan through a photography darkroom. Red safety light glows on silver gelatin prints. Film photography aesthetic. Timeless.",
    style: "gradient",
    colors: ["#94a3b8", "#475569", "#0a0b0e"],
  },
  {
    name: "PaperWild",
    category: "Creative",
    description: "Illustration studio with textured analog warmth",
    tags: ["Illustration", "Amber", "Analog"],
    gradient: "from-stone-600 via-stone-800 to-neutral-950",
    accent: "#fcd34d",
    prompt: "Macro of old paper texture with watercolor paint bleeding at edges. Warm analog studio. Illustration and craft aesthetic.",
    style: "wave",
    colors: ["#d97706", "#eab308", "#191202"],
  },

  // ── Music ───────────────────────────────────────────────────────────────────
  {
    name: "WaveForm",
    category: "Music",
    description: "Music streaming platform with soundwave visuals",
    tags: ["Streaming", "Indigo", "Audio"],
    gradient: "from-indigo-700 via-violet-800 to-indigo-950",
    accent: "#a5b4fc",
    prompt: "Abstract 3D audio waveform pulsing in deep indigo space. Sound visualized as flowing light ribbons. Music platform aesthetic.",
    style: "wave",
    colors: ["#6366f1", "#7c3aed", "#07061a"],
  },
  {
    name: "BeatLab",
    category: "Music",
    description: "Beat production studio with dark club energy",
    tags: ["Production", "Rose", "Club"],
    gradient: "from-rose-800 via-pink-900 to-rose-950",
    accent: "#f43f5e",
    prompt: "Cinematic shot of DJ mixer with glowing VU meters. Dark club atmosphere. Red and pink neon. Bass-heavy visual energy.",
    style: "geometric",
    colors: ["#f43f5e", "#be185d", "#190310"],
  },

  // ── Fitness ──────────────────────────────────────────────────────────────────
  {
    name: "IronPeak",
    category: "Fitness",
    description: "Premium gym brand with raw power aesthetics",
    tags: ["Gym", "Gray", "Raw"],
    gradient: "from-gray-600 via-zinc-700 to-gray-900",
    accent: "#d1d5db",
    prompt: "Cinematic slow motion of chalk dust exploding from weights. Dark gym atmosphere. Dramatic rim lighting. Raw athletic power.",
    style: "particles",
    colors: ["#d1d5db", "#52525b", "#0b0b0d"],
  },
  {
    name: "ZenFlow",
    category: "Fitness",
    description: "Yoga & meditation app with serene nature visuals",
    tags: ["Yoga", "Teal", "Serene"],
    gradient: "from-teal-600 via-emerald-700 to-teal-900",
    accent: "#6ee7b7",
    prompt: "Aerial view of morning mist over a glassy mountain lake. Teal and emerald tones. Absolute stillness. Meditation and peace.",
    style: "wave",
    colors: ["#2dd4bf", "#10b981", "#02120e"],
  },
];

export function findPreset(name: string): Preset | undefined {
  const target = name.trim().toLowerCase();
  return PRESETS.find((p) => p.name.toLowerCase() === target);
}
