import type { Style2D } from "@/lib/generate2DFrames";
import type { Section } from "@/lib/siteSchema";

export interface TemplateTheme {
  fontDisplay?: string;
  fontBody?: string;
  scale?: "compact" | "editorial" | "poster";
  displayWeight?: number;
  displayCase?: "none" | "upper";
  displayTracking?: number;
  ink?: string;
  muted?: string;
  accent?: string;
  accentText?: string;
  radius?: number;
}

export interface Template {
  slug: string;
  name: string;
  tagline: string;
  category: string;
  tags: string[];
  style: Style2D;
  colors: [string, string, string];
  /** Tailwind gradient for the gallery card, so a card reads before frames render. */
  gradient: string;
  theme: TemplateTheme;
  sections: Section[];
}

const INTRO_BUFFER = 1000;

/** Matches the exporter and the skill: the leading spacer plus every section's own track. */
export function templateScrollHeight(t: Template): number {
  return t.sections.reduce((acc, s) => acc + (s.scrollHeight ?? 1000), 0) + INTRO_BUFFER;
}

/** Content sections a visitor gets. */
export function templateSectionCount(t: Template): number {
  return t.sections.filter((s) => s.kind !== "spacer").length;
}

export function templateBySlug(slug: string): Template | undefined {
  return TEMPLATES.find((t) => t.slug === slug);
}

export function templateCategories(): string[] {
  return [...new Set(TEMPLATES.map((t) => t.category))].sort();
}

export const TEMPLATES: Template[] = [
  {
    slug: "orbitcrm",
    name: "OrbitCRM",
    tagline: "A revenue tool that reads like an argument, not a feature list",
    category: "SaaS",
    tags: ["Dark", "Violet", "Product-led"],
    style: "gradient",
    colors: ["#7c3aed", "#2563eb", "#0f172a"],
    gradient: "from-violet-800 via-purple-900 to-violet-950",
    theme: {
      fontDisplay: "Archivo", fontBody: "IBM Plex Sans", scale: "editorial",
      displayWeight: 800, ink: "#f1eefb", muted: "rgba(241,238,251,0.72)",
      accent: "#5b34a8", accentText: "#d6c6f5", radius: 8,
    },
    sections: [
      {
        kind: "statement", layout: "center", reveal: "mask",
        eyebrow: "Introducing OrbitCRM",
        heading: "Close deals at the speed of light.",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "The problem",
        heading: "Your CRM is a filing cabinet",
        body: "Reps update it on Friday afternoon for a manager who reads it on Monday. By then the deal has moved twice and nobody trusts the number on the board.",
        scrollHeight: 1500,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Pipeline",
        heading: "Your pipeline, finally alive",
        body: "Drag-and-drop stages, real-time probability scoring, and next-step suggestions drawn from the deals your team already won. The board updates as the work happens, not after it.",
        scrollHeight: 1500,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Forecasting",
        heading: "A number you can defend",
        body: "Every forecast shows its working: which deals carry it, what changed this week, and which of last quarter's assumptions turned out wrong. Bring it to a board meeting without a spreadsheet on the side.",
        scrollHeight: 1500,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Handover",
        heading: "Nothing lives in one rep's head",
        body: "Calls, threads and commitments attach to the deal rather than the person. When someone leaves or takes a week off, the next person opens the record and knows where things stand.",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Built for revenue teams",
        heading: "Scales past the point most tools break",
        body: "Role-based access, a full audit log, and single sign-on, so a security review is a conversation rather than a project. Territories and quotas change without a support ticket.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "scale",
        heading: "Start closing this week",
        body: "Import from a spreadsheet or your current CRM, keep the mess, clean it up later. Most teams are running their first pipeline review the same afternoon.",
        ctaLabel: "Start free trial", ctaHref: "#signup",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "atlas-studio",
    name: "Atlas Studio",
    tagline: "A design studio page that lets the work do the talking",
    category: "Agency",
    tags: ["Editorial", "Serif", "Restrained"],
    style: "wave",
    colors: ["#0b1f2a", "#14505f", "#061218"],
    gradient: "from-slate-800 via-teal-900 to-slate-950",
    theme: {
      fontDisplay: "Playfair Display", fontBody: "Lato", scale: "poster",
      displayWeight: 700, displayTracking: -0.025, ink: "#f3f1ea",
      muted: "rgba(243,241,234,0.7)", accent: "#1f6b74", accentText: "#a7dbe0", radius: 0,
    },
    sections: [
      {
        kind: "statement", layout: "lower-third", reveal: "mask",
        heading: "We build the thing you cannot stop looking at.",
        scrollHeight: 1600,
      },
      {
        layout: "lower-third", reveal: "stagger",
        eyebrow: "How we work",
        heading: "Six weeks, one team, no handoff",
        body: "Strategy, design and build in the same room. Nothing gets thrown over a wall, so nothing arrives diluted. You talk to the people making it, every week, until it ships.",
        scrollHeight: 1500,
      },
      {
        layout: "left", reveal: "fade",
        eyebrow: "What you get",
        heading: "A running thing, not a deck",
        body: "We do not sell you a strategy document to implement later. Week six ends with something on a real domain that real people can use, and the reasoning written down beside it.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 900 },
      {
        kind: "statement", layout: "center", reveal: "scale",
        heading: "Selected work, 2019 to now.",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "stagger",
        eyebrow: "Who we work with",
        heading: "Small teams with something specific to say",
        body: "Founders past the first version, studios launching a second line, institutions that have outgrown the site a volunteer built. If the brief is to look like everyone else, we are the wrong studio.",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "fade",
        eyebrow: "The awkward part",
        heading: "We will push back",
        body: "If the homepage is trying to say five things we will tell you which four to cut. That conversation is the work, and it is easier in week one than in week five.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "fade",
        heading: "Tell us what you are making",
        body: "A paragraph is enough to start. We will come back with what we think the hard part is and whether we are the right people for it.",
        ctaLabel: "Start a project", ctaHref: "#contact",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "meridian-watch",
    name: "Meridian",
    tagline: "A single-product page built around one object",
    category: "Product",
    tags: ["Luxury", "Warm", "Minimal"],
    style: "gradient",
    colors: ["#1a0f07", "#7a3d10", "#0d0704"],
    gradient: "from-amber-900 via-orange-950 to-stone-950",
    theme: {
      fontDisplay: "Archivo", fontBody: "IBM Plex Sans", scale: "poster",
      displayWeight: 800, displayCase: "upper", displayTracking: -0.02,
      ink: "#f7efe6", muted: "rgba(247,239,230,0.7)",
      accent: "#a94b0d", accentText: "#f8c9aa", radius: 2,
    },
    sections: [
      {
        kind: "statement", layout: "center", reveal: "mask",
        eyebrow: "Meridian 01",
        heading: "Machined from one billet.",
        scrollHeight: 1500,
      },
      { kind: "spacer", scrollHeight: 800 },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Movement",
        heading: "Eleven parts. Each one load bearing.",
        body: "No decoration, no filler plate, nothing added to look expensive. What you see holding the hands is what holds the hands. Service it in twenty years and the parts will still make sense.",
        scrollHeight: 1600,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Case",
        heading: "Brushed by hand, twice",
        body: "Once to flatten the mill marks, once at a right angle so the light moves across it rather than glinting off it. It takes a person four minutes and no machine has matched it.",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Dial",
        heading: "Printed, not stuck on",
        body: "The markers are laid into the brass rather than applied over it, so there is no lip to catch dust and nothing to lift in the heat. Read it in direct sun without tilting your wrist.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Strap",
        heading: "One buckle, no tools",
        body: "Quick-release bars, so changing a strap is a ten-second job on the kitchen table. Two are in the box: oiled leather for most days, rubber for the days you forget you have it on.",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Ownership",
        heading: "It is meant to be worn",
        body: "Sapphire front, hundred metres of water resistance, and a caseback that comes off with a standard wrench. Scratches are not damage. The second owner should be able to service it too.",
        scrollHeight: 1400,
      },
      {
        layout: "center", reveal: "scale",
        heading: "Four hundred made",
        body: "Then the tooling is retired. Reserving holds one from the run and costs nothing until yours is machined.",
        ctaLabel: "Reserve one", ctaHref: "#reserve",
        scrollHeight: 1100,
      },
    ],
  },
  {
    slug: "kiln-coffee",
    name: "Kiln",
    tagline: "A roastery page that smells like the room",
    category: "Food & Drink",
    tags: ["Warm", "Editorial", "Craft"],
    style: "particles",
    colors: ["#160d08", "#6b3418", "#0b0605"],
    gradient: "from-orange-950 via-amber-950 to-stone-950",
    theme: {
      fontDisplay: "Fraunces", fontBody: "Karla", scale: "editorial",
      displayWeight: 700, displayTracking: -0.02, ink: "#f6ece2",
      muted: "rgba(246,236,226,0.72)", accent: "#8a4318", accentText: "#f2c39c", radius: 12,
    },
    sections: [
      {
        kind: "statement", layout: "lower-third", reveal: "fade",
        eyebrow: "Kiln Roastery",
        heading: "Roasted this morning. Ground when you order.",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Sourcing",
        heading: "Two farms. Both on first-name terms.",
        body: "We buy the whole lot or none of it, which means the price is agreed before harvest and the farmer is not gambling on us. It also means we run out, and we would rather run out.",
        scrollHeight: 1500,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "The roast",
        heading: "Light enough to taste the fruit",
        body: "Anything darker is a decision to hide the bean. We would rather sell you something that tastes of where it grew, even when that is less forgiving in the cup.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Freshness",
        heading: "Bags are dated, not stamped",
        body: "The date on the bag is the day it left the drum, not a best-before eighteen months out. Coffee is at its best from four days to four weeks, and we would rather you knew that.",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Brewing",
        heading: "A recipe on every bag",
        body: "Dose, grind, water temperature and time, worked out on the kit most people actually own. Follow it once, then change one thing at a time until it tastes like yours.",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "The shop",
        heading: "Open at seven, closed on Mondays",
        body: "The roaster runs Tuesday and Thursday mornings, so those are the days the room smells like the reason we do this. There is a bench, and nobody will rush you off it.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "scale",
        heading: "Subscribe, or just try a bag",
        body: "Subscriptions ship the morning after roasting and pause whenever you like. If you are not sure yet, one bag is a smaller commitment than a conversation.",
        ctaLabel: "Order coffee", ctaHref: "#shop",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "northlight",
    name: "Northlight",
    tagline: "A photographer's portfolio that gets out of the way",
    category: "Portfolio",
    tags: ["Cold", "Quiet", "Image-led"],
    style: "wave",
    colors: ["#050a12", "#123a52", "#02060b"],
    gradient: "from-sky-950 via-slate-900 to-black",
    theme: {
      fontDisplay: "Space Grotesk", fontBody: "Inter", scale: "compact",
      displayWeight: 600, displayTracking: 0.01, ink: "#e9f1f6",
      muted: "rgba(233,241,246,0.68)", accent: "#1f5f78", accentText: "#a9d9ec", radius: 4,
    },
    sections: [
      {
        layout: "lower-third", reveal: "fade",
        eyebrow: "Northlight",
        heading: "Landscape work, mostly at dawn",
        body: "Iceland, the Faroes, and a lot of waiting in cars. The light I want lasts about forty minutes and does not care whether I am ready.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 800 },
      {
        layout: "lower-third", reveal: "fade",
        eyebrow: "Series 01",
        heading: "Sixty-one days of the same shoreline",
        body: "Same tripod holes, same hour, every day through a winter. The interesting part is how little repeats, and how much of that only shows up when the frames sit next to each other.",
        scrollHeight: 1500,
      },
      {
        layout: "left", reveal: "fade",
        eyebrow: "Series 02",
        heading: "The road north, in one pass",
        body: "Nine hundred kilometres shot in four days without turning back for anything. What is in the edit is what the road gave up in order, which is not how I usually work.",
        scrollHeight: 1400,
      },
      {
        layout: "lower-third", reveal: "fade",
        eyebrow: "Method",
        heading: "One camera, two lenses, no filters",
        body: "Everything is a single exposure. If the sky is brighter than the ground, the sky is brighter than the ground. I would rather lose the frame than assemble one that was never there.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Prints",
        heading: "Editions of nine",
        body: "Hand-printed, signed on the back, shipped flat. Cotton rag, pigment ink, and a size that fits through a standard doorway without a conversation about installers.",
        scrollHeight: 1200,
      },
      {
        layout: "lower-third", reveal: "fade",
        eyebrow: "Commissions",
        heading: "I travel, but not in a hurry",
        body: "Editorial and architectural work, usually a week on location because the weather decides the schedule. If the deadline is Tuesday and the forecast is wrong, I will tell you before you book.",
        scrollHeight: 1300,
      },
      {
        layout: "center", reveal: "rise",
        heading: "Commissions open for spring",
        body: "Tell me where and roughly when. I will say honestly whether the light will be doing anything worth photographing.",
        ctaLabel: "Get in touch", ctaHref: "#contact",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "signal-conf",
    name: "Signal",
    tagline: "A conference page that answers the only three questions",
    category: "Event",
    tags: ["Bold", "Cyan", "Dated"],
    style: "geometric",
    colors: ["#03121a", "#0a5f6e", "#010a0f"],
    gradient: "from-cyan-900 via-teal-950 to-slate-950",
    theme: {
      fontDisplay: "Oswald", fontBody: "Roboto", scale: "poster",
      displayWeight: 600, displayCase: "upper", displayTracking: 0.015,
      ink: "#e6f6f8", muted: "rgba(230,246,248,0.7)",
      accent: "#12666f", accentText: "#9fe3ec", radius: 0,
    },
    sections: [
      {
        kind: "statement", layout: "center", reveal: "mask",
        eyebrow: "March 14 to 16 · Lisbon",
        heading: "Signal 2027",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Programme",
        heading: "Three days, one track, no parallel sessions",
        body: "Everyone sees the same talks, so the hallway conversation is about the thing you all just watched. Nobody spends a coffee break comparing notes on rooms they could not be in.",
        scrollHeight: 1500,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Speakers",
        heading: "Twenty-two people who build things",
        body: "No keynote sponsors, no vendor pitches. If someone is on stage it is because they shipped something, and the talk is about how it actually went rather than how it was planned.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "The format",
        heading: "Thirty minutes, then questions",
        body: "No talk runs long, because the schedule is the one promise we can keep. Speakers stay in the room afterwards, so the question you thought of on the way out still has somewhere to go.",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Getting there",
        heading: "One venue, one street, no shuttle",
        body: "Talks, food and the evening events happen in the same building. Two metro stops from the centre, and the hotels we have blocked are all inside a fifteen-minute walk.",
        scrollHeight: 1300,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Who comes",
        heading: "Engineers, designers, and the people who decide",
        body: "Roughly a third each, on purpose. The talks assume you build things and the breaks assume you would like to meet someone who does the other half of your job.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "scale",
        eyebrow: "Tickets",
        heading: "Four hundred seats",
        body: "One price, lunch included, no tiers and no upsell. Student and community rates exist and do not require you to explain yourself.",
        ctaLabel: "Get a ticket", ctaHref: "#tickets",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "quarry-fitness",
    name: "Quarry",
    tagline: "A gym page with no stock photography energy",
    category: "Fitness",
    tags: ["Hard", "Monochrome", "Direct"],
    style: "geometric",
    colors: ["#0a0c0f", "#2b343d", "#050607"],
    gradient: "from-zinc-800 via-slate-900 to-black",
    theme: {
      fontDisplay: "Oswald", fontBody: "Roboto", scale: "poster",
      displayWeight: 700, displayCase: "upper", displayTracking: 0.02,
      ink: "#eef1f4", muted: "rgba(238,241,244,0.68)",
      accent: "#4b555f", accentText: "#c9d3dc", radius: 0,
    },
    sections: [
      {
        kind: "statement", layout: "lower-third", reveal: "mask",
        heading: "It is going to be hard. That is the product.",
        scrollHeight: 1500,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Coaching",
        heading: "One coach, twelve people, no mirrors",
        body: "You get corrected out loud, in front of everyone, because that is the fastest way to stop doing it wrong. Nobody here is watching you. They are all busy being corrected too.",
        scrollHeight: 1500,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "The sessions",
        heading: "Forty-five minutes, written on the board",
        body: "You walk in knowing exactly what you are doing and roughly how much it will hurt. The programme runs in six-week blocks, so the thing you were bad at in week one comes back in week five.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Starting out",
        heading: "Nobody starts fit",
        body: "Every movement has a version you can do today, and the coach picks it rather than you guessing. The first month is mostly learning to load things properly, which is slower and less impressive than it looks online.",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "The room",
        heading: "Barbells, rings, and a rowing machine",
        body: "No screens, no class playlists you did not choose, no machine that isolates one muscle for a reason nobody can explain. Chalk, a clock, and enough space to drop something safely.",
        scrollHeight: 1300,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Membership",
        heading: "Month to month, cancel whenever",
        body: "No twelve-month contract. If it stops being worth it, leaving should be easy, and you should not have to phone anyone to do it.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "scale",
        heading: "First session is free",
        body: "Come and do the actual class, not a tour. If it is not for you, that is a useful thing to find out in forty-five minutes rather than six weeks.",
        ctaLabel: "Book it", ctaHref: "#book",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "ledger-fintech",
    name: "Ledger",
    tagline: "A fintech page that leads with the number",
    category: "SaaS",
    tags: ["Cool", "Dense", "Technical"],
    style: "gradient",
    colors: ["#02110f", "#0c4a42", "#010807"],
    gradient: "from-emerald-900 via-teal-950 to-black",
    theme: {
      fontDisplay: "Space Grotesk", fontBody: "Inter", scale: "compact",
      displayWeight: 700, ink: "#e8f5f1", muted: "rgba(232,245,241,0.7)",
      accent: "#0f5f55", accentText: "#93dccf", radius: 6,
    },
    sections: [
      {
        layout: "upper-third", reveal: "fade",
        eyebrow: "Ledger",
        heading: "Close the month in four days, not fourteen",
        body: "Reconciliation that runs continuously instead of in a panic at quarter end. The work is spread across the month, so the last week stops being the whole job.",
        scrollHeight: 1400,
      },
      {
        layout: "center", reveal: "rise",
        eyebrow: "The problem",
        heading: "Close is a spreadsheet held together by one person",
        body: "Somebody knows which tab to refresh first and in what order the exports have to land. When they take a holiday, the close takes a week longer and nobody can say precisely why.",
        scrollHeight: 1500,
      },
      {
        layout: "upper-third", reveal: "fade",
        eyebrow: "Coverage",
        heading: "Every account, one ledger",
        body: "Nineteen banks, six payment processors, and your own internal transfers, matched on the same rules engine. New accounts inherit the rules rather than starting a new spreadsheet.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "center", reveal: "rise",
        eyebrow: "Exceptions",
        heading: "The queue is the point",
        body: "Matches happen without you. What lands in the queue is the handful of things that genuinely need a human, with the reason it failed to match written next to it in words.",
        scrollHeight: 1400,
      },
      {
        layout: "upper-third", reveal: "fade",
        eyebrow: "Audit",
        heading: "Every change has a name on it",
        body: "Immutable history, exportable in the format your auditor asks for rather than the one we prefer. Nothing is edited in place, so the question is always who and when rather than whether.",
        scrollHeight: 1400,
      },
      {
        layout: "center", reveal: "rise",
        eyebrow: "Getting in",
        heading: "Read-only until you say otherwise",
        body: "We connect with read access, run a parallel close beside your existing one, and show you where the two disagree. Nothing writes back to your bank or your ledger without you turning it on.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "rise",
        heading: "See it against your own data",
        body: "A walkthrough uses your last closed month, not a demo tenant. Forty minutes, and you keep the reconciliation it produces either way.",
        ctaLabel: "Book a walkthrough", ctaHref: "#demo",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "harbour-estate",
    name: "Harbour",
    tagline: "A property listing that sells the view, not the square footage",
    category: "Real Estate",
    tags: ["Calm", "Blue", "Spacious"],
    style: "wave",
    colors: ["#04121c", "#11526b", "#020a10"],
    gradient: "from-sky-900 via-slate-900 to-slate-950",
    theme: {
      fontDisplay: "Playfair Display", fontBody: "Lato", scale: "editorial",
      displayWeight: 700, displayTracking: -0.02, ink: "#f0f5f8",
      muted: "rgba(240,245,248,0.72)", accent: "#1a5d78", accentText: "#a6d7e8", radius: 10,
    },
    sections: [
      {
        kind: "statement", layout: "lower-third", reveal: "mask",
        eyebrow: "Harbour House",
        heading: "The water is forty metres away.",
        scrollHeight: 1500,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "The house",
        heading: "Built in 1908, rewired in 2024",
        body: "Original floors, original windows, none of the original plumbing. Four bedrooms, two of them facing the estuary, and a kitchen that was moved to the back where the light is better.",
        scrollHeight: 1500,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "The rooms",
        heading: "Two hundred and ten square metres",
        body: "Arranged as they were meant to be rather than knocked into one space. The sitting room keeps its fireplace and its door, which matters more in February than the open plan does in July.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Outside",
        heading: "A garden that ends at the wall",
        body: "Sixty feet, south-facing, with a gate onto the coast path. There is a shed with power to it and a mooring that transfers with the house if you want it.",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "The village",
        heading: "A shop, a pub, and a train every hour",
        body: "Fifty-one minutes to the city, which is close enough to commute and far enough to hear the tide. The primary school is a four-minute walk and takes children from the lane.",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Honestly",
        heading: "Things you should know",
        body: "The road floods twice a winter at the very high tides and clears within the hour. The roof was redone in 2019 and the survey is available before you ask for it.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "scale",
        heading: "Viewings from Saturday",
        body: "Forty minutes each, and worth timing near high water. We will send the survey, the floor plan and the tide table with the confirmation.",
        ctaLabel: "Arrange a viewing", ctaHref: "#viewing",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "field-notes",
    name: "Field Notes",
    tagline: "A long-form essay layout for one piece of writing",
    category: "Editorial",
    tags: ["Quiet", "Serif", "Text-first"],
    style: "particles",
    colors: ["#0a0910", "#2d2543", "#050409"],
    gradient: "from-indigo-950 via-slate-900 to-black",
    theme: {
      fontDisplay: "Fraunces", fontBody: "Karla", scale: "editorial",
      displayWeight: 600, displayTracking: -0.015, ink: "#f0edf7",
      muted: "rgba(240,237,247,0.72)", accent: "#4a3a7a", accentText: "#cfc3ee", radius: 14,
    },
    sections: [
      {
        layout: "lower-third", reveal: "fade",
        eyebrow: "Essay · 12 min",
        heading: "What we lost when maps stopped being wrong",
        body: "On blank spaces, false certainty, and why the most useful map is the one that tells you where it stops knowing.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 800 },
      {
        layout: "lower-third", reveal: "stagger",
        heading: "Part one: the blank spaces",
        body: "A map that admits it does not know something is more honest than one that quietly guesses. We traded the first for the second and called it progress, because a continuous surface is easier to sell than an edge.",
        scrollHeight: 1500,
      },
      {
        layout: "left", reveal: "fade",
        heading: "The cartographer's confession",
        body: "The old surveys carried a line where the survey ended. Past it, nothing was drawn, and the absence was the most accurate mark on the sheet. It told you to slow down, which no modern map has ever done.",
        scrollHeight: 1400,
      },
      {
        layout: "lower-third", reveal: "stagger",
        heading: "Part two: the cost of certainty",
        body: "Every seam smoothed over is a decision someone made on your behalf, in a room you were not in, about a place you are about to walk through. The smoothing is invisible, which is exactly what makes it expensive.",
        scrollHeight: 1500,
      },
      {
        layout: "right", reveal: "fade",
        heading: "What the seam was holding",
        body: "Two surveys meeting at a river, taken eleven years apart, disagreeing by ninety metres. The disagreement was the information. Averaging it away produced a number that was wrong in a new and quieter way.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "lower-third", reveal: "stagger",
        heading: "Part three: drawing the edge back in",
        body: "Nobody is asking for worse maps. The argument is for maps that mark their own confidence, the way a good forecast gives you a range instead of a single reassuring number you will plan around.",
        scrollHeight: 1400,
      },
      {
        layout: "center", reveal: "scale",
        heading: "Subscribe for the next one",
        body: "One essay a month, sent when it is finished rather than on a schedule. No newsletter, no digest, nothing else in the envelope.",
        ctaLabel: "Get essays by email", ctaHref: "#subscribe",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "pulse-app",
    name: "Pulse",
    tagline: "A mobile app launch page, one feature per screen",
    category: "Product",
    tags: ["Vivid", "Playful", "App"],
    style: "particles",
    colors: ["#0b0418", "#5b1f8a", "#060210"],
    gradient: "from-fuchsia-900 via-purple-950 to-black",
    theme: {
      fontDisplay: "Archivo", fontBody: "Inter", scale: "poster",
      displayWeight: 800, displayTracking: -0.03, ink: "#f6eefb",
      muted: "rgba(246,238,251,0.72)", accent: "#7a3aa8", accentText: "#e2c2f5", radius: 20,
    },
    sections: [
      {
        kind: "statement", layout: "center", reveal: "scale",
        eyebrow: "Pulse",
        heading: "Your week, on one screen.",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Planning",
        heading: "Plan in minutes, not evenings",
        body: "Drag a block, drop it on a day. That is the whole interaction, and it is deliberately the only one. There is no project, no label and no board to set up first.",
        scrollHeight: 1500,
      },
      {
        layout: "right", reveal: "mask",
        eyebrow: "Focus",
        heading: "One thing at a time, enforced",
        body: "Pulse hides everything you are not doing right now. You can turn that off. You will turn it back on, usually within a day, which is the most useful thing we learned building it.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Rolling over",
        heading: "Unfinished work moves itself",
        body: "Anything you did not get to appears at the top of tomorrow, marked with how many times it has moved. After the third time it asks whether you actually intend to do it.",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "mask",
        eyebrow: "Offline",
        heading: "Works on a plane",
        body: "Everything is on the device first and syncs when there is a connection. No spinner, no empty state, no screen that exists only to tell you the network is gone.",
        scrollHeight: 1300,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Your data",
        heading: "Export it whenever, in plain text",
        body: "One file, readable without us, including everything you ever wrote. We would rather you stayed because it is good than because leaving is annoying.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "scale",
        heading: "Free while we are in beta",
        body: "No card, no trial clock. When there is a price it will be a small one, and beta users keep this version working either way.",
        ctaLabel: "Get the app", ctaHref: "#download",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "cinder-restaurant",
    name: "Cinder",
    tagline: "A restaurant page that reads like the menu",
    category: "Food & Drink",
    tags: ["Dark", "Ember", "Intimate"],
    style: "gradient",
    colors: ["#120604", "#5e2109", "#080302"],
    gradient: "from-red-950 via-orange-950 to-black",
    theme: {
      fontDisplay: "Playfair Display", fontBody: "Lato", scale: "poster",
      displayWeight: 700, displayTracking: -0.02, ink: "#f8ece3",
      muted: "rgba(248,236,227,0.7)", accent: "#973f11", accentText: "#f6c4a0", radius: 4,
    },
    sections: [
      {
        kind: "statement", layout: "lower-third", reveal: "mask",
        eyebrow: "Cinder",
        heading: "Everything here touched fire.",
        scrollHeight: 1500,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "The kitchen",
        heading: "One hearth, no gas, no induction",
        body: "Twelve dishes a night because that is what one fire can do properly. The menu changes when the delivery does, which means it changes most days and is never printed in advance.",
        scrollHeight: 1500,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "The cooking",
        heading: "Wood, and the time it takes",
        body: "Oak and a little beech, lit at two in the afternoon for a seven o'clock service. Nothing is finished to order, so the kitchen cannot rush and neither, happily, can we.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "The room",
        heading: "Twenty-six seats, one long table",
        body: "You will be sitting next to someone you do not know. Most people decide they like this by the second course, and the ones who do not are usually glad they tried it.",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Drinks",
        heading: "A short list, mostly from nearby",
        body: "Fourteen bottles, six by the glass, and a non-alcoholic list that someone actually thought about. If you tell us what you are eating we will pick for you and be right most of the time.",
        scrollHeight: 1300,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Before you come",
        heading: "What we can and cannot do",
        body: "Vegetarian every night with notice. Coeliac is difficult and we would rather say so than improvise. The room is up three steps and we will help with them.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "scale",
        heading: "Bookings open on the first",
        body: "One month ahead, at nine in the morning, and they go in about an hour. Two seats at the end of the table are kept back for whoever walks in.",
        ctaLabel: "Reserve a seat", ctaHref: "#book",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "beacon-nonprofit",
    name: "Beacon",
    tagline: "A cause page that asks once, clearly",
    category: "Nonprofit",
    tags: ["Warm", "Human", "Direct"],
    style: "wave",
    colors: ["#0c1108", "#3d5417", "#050803"],
    gradient: "from-lime-950 via-green-950 to-black",
    theme: {
      fontDisplay: "Archivo", fontBody: "IBM Plex Sans", scale: "editorial",
      displayWeight: 700, ink: "#f0f4e9", muted: "rgba(240,244,233,0.72)",
      accent: "#3f5c1a", accentText: "#c6dfa0", radius: 8,
    },
    sections: [
      {
        kind: "statement", layout: "center", reveal: "fade",
        eyebrow: "Beacon",
        heading: "Eleven thousand homes still have no meter.",
        scrollHeight: 1500,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Why it matters",
        heading: "You cannot argue with a bill you cannot read",
        body: "Without a meter a household pays an estimate, and the estimate is almost always high. Nobody in that house can prove otherwise, which is the whole problem in one sentence.",
        scrollHeight: 1500,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "What we do",
        heading: "We install, then we leave",
        body: "No ongoing fee, no data harvesting, no branding on the box. The household owns the meter from the day it goes in, and nothing about it reports back to us.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "How it works",
        heading: "Local fitters, trained and paid properly",
        body: "We do not fly people in. Fitters are hired from the districts they work in, certified at our cost, and keep the qualification whether they stay with us or not.",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Where it goes",
        heading: "Ninety-one pence in the pound",
        body: "Published quarterly, audited annually, and broken down per district so you can see the one nearest you. The other nine pence is fitters' training and the van.",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "What we will not do",
        heading: "No photographs of anyone's kitchen",
        body: "We do not use images of the households we work with to raise money. If a story is told here, it is because the person telling it asked to, in their own words.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "scale",
        heading: "Fund a meter",
        body: "Forty pounds covers one installation, including the fitter's time and the certificate the household keeps. You can give once; there is no subscription to cancel later.",
        ctaLabel: "Donate", ctaHref: "#donate",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "vellum-books",
    name: "Vellum",
    tagline: "A book launch page with room to breathe",
    category: "Editorial",
    tags: ["Paper", "Serif", "Slow"],
    style: "particles",
    colors: ["#100c07", "#4a3a22", "#070502"],
    gradient: "from-yellow-950 via-stone-900 to-black",
    theme: {
      fontDisplay: "Fraunces", fontBody: "Karla", scale: "poster",
      displayWeight: 700, displayTracking: -0.03, ink: "#f5efe3",
      muted: "rgba(245,239,227,0.72)", accent: "#6d5324", accentText: "#e3cfa3", radius: 6,
    },
    sections: [
      {
        kind: "statement", layout: "center", reveal: "mask",
        eyebrow: "Out in April",
        heading: "The Salt Road",
        scrollHeight: 1500,
      },
      { kind: "spacer", scrollHeight: 800 },
      {
        layout: "lower-third", reveal: "stagger",
        eyebrow: "The book",
        heading: "Four hundred pages, one journey",
        body: "A trade route, the people who kept it open, and what happened in the eighty years after it closed. Told as a single walk from one end to the other rather than as a survey.",
        scrollHeight: 1500,
      },
      {
        layout: "left", reveal: "fade",
        eyebrow: "The research",
        heading: "Six years, mostly in archives",
        body: "Customs ledgers, three surviving letter collections, and a fortnight on the road itself with a translator. Where the record stops, the book says so instead of filling the gap.",
        scrollHeight: 1400,
      },
      {
        layout: "lower-third", reveal: "stagger",
        eyebrow: "Why now",
        heading: "The route reopened in 2019",
        body: "Not as a trade road but as a border crossing, which is how the archive came out of a basement in the first place. Half the material in the book had never been read.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "right", reveal: "fade",
        eyebrow: "The object",
        heading: "Sewn, not glued",
        body: "Cloth over boards, a folded map in the back, and paper heavy enough that the map does not show through the last chapter. It will open flat on a table in twenty years.",
        scrollHeight: 1300,
      },
      {
        layout: "center", reveal: "scale",
        heading: "Signed first editions",
        body: "Numbered to five hundred, signed on the title page, and shipped in the first week of April before the trade edition.",
        ctaLabel: "Pre-order", ctaHref: "#preorder",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "forge-devtool",
    name: "Forge",
    tagline: "A developer tool page written for people who read docs",
    category: "SaaS",
    tags: ["Terminal", "Dense", "Technical"],
    style: "geometric",
    colors: ["#060810", "#1f2a44", "#03040a"],
    gradient: "from-slate-800 via-indigo-950 to-black",
    theme: {
      fontDisplay: "Space Grotesk", fontBody: "Inter", scale: "compact",
      displayWeight: 700, ink: "#e9ecf6", muted: "rgba(233,236,246,0.7)",
      accent: "#2f3f6b", accentText: "#aebbe6", radius: 4,
    },
    sections: [
      {
        layout: "upper-third", reveal: "fade",
        eyebrow: "Forge",
        heading: "Builds that finish before you switch tabs",
        body: "Content-addressed caching, so the second build of anything is a lookup. The cache is shared, which means your build is usually somebody else's lookup.",
        scrollHeight: 1400,
      },
      {
        layout: "center", reveal: "rise",
        eyebrow: "How",
        heading: "Nothing runs twice",
        body: "Every task is keyed on its inputs. Change one file and exactly the work that depends on it re-runs, which is a smaller set than your current build system assumes.",
        scrollHeight: 1500,
      },
      {
        layout: "upper-third", reveal: "fade",
        eyebrow: "On CI",
        heading: "The same cache your laptop used",
        body: "CI does not start cold. It reads the artefacts your machine already produced, so a pull request that changes a README does not rebuild the world to prove it.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "center", reveal: "rise",
        eyebrow: "When it is wrong",
        heading: "Explain, not just run",
        body: "Ask why a task re-ran and Forge prints the input that changed and the hash on either side. Cache misses stop being a mystery you work around with a clean build.",
        scrollHeight: 1400,
      },
      {
        layout: "upper-third", reveal: "fade",
        eyebrow: "Adoption",
        heading: "One file, then delete it if you hate it",
        body: "Forge reads your existing scripts. There is no migration and no lock-in to unwind, and removing the file leaves you exactly where you started.",
        scrollHeight: 1400,
      },
      {
        layout: "center", reveal: "rise",
        eyebrow: "What it is not",
        heading: "It will not fix a slow test suite",
        body: "Forge skips work it has already done. It cannot make work it has not done any faster, and a test that takes four minutes will still take four minutes the first time.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "rise",
        heading: "Try it on your slowest repo",
        body: "The docs start with the honest version: what to add, what it will and will not cache, and how to tell whether it helped.",
        ctaLabel: "Read the docs", ctaHref: "#docs",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "solstice-travel",
    name: "Solstice",
    tagline: "A travel page that sells one trip properly",
    category: "Travel",
    tags: ["Golden", "Wide", "Cinematic"],
    style: "gradient",
    colors: ["#150c04", "#8a5310", "#0a0602"],
    gradient: "from-amber-800 via-orange-900 to-stone-950",
    theme: {
      fontDisplay: "Playfair Display", fontBody: "Lato", scale: "poster",
      displayWeight: 700, displayTracking: -0.025, ink: "#f9f0e2",
      muted: "rgba(249,240,226,0.72)", accent: "#8d5311", accentText: "#f4cf9c", radius: 16,
    },
    sections: [
      {
        kind: "statement", layout: "lower-third", reveal: "mask",
        eyebrow: "Nine days · Atacama",
        heading: "The driest place that still has a sky.",
        scrollHeight: 1500,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "The route",
        heading: "Three valleys, one salt flat, no coaches",
        body: "Small vehicles, local guides, and the kind of pace that lets you stop when the light does something. Two nights in the same bed twice, so it is not nine days of packing.",
        scrollHeight: 1500,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Nights",
        heading: "Two of them outside",
        body: "At four thousand metres with no town for eighty kilometres, which is the entire reason to come. Proper tents, proper bedding, and someone who has done this two hundred times.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "The altitude",
        heading: "We go up slowly on purpose",
        body: "The first three days sit below three thousand metres because that is what makes the last three enjoyable. Nobody is asked to push through a headache to keep a schedule.",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Who guides it",
        heading: "People from the valleys we cross",
        body: "Guides are hired locally, paid a day rate rather than commission, and know which road washed out last week. They are not reading from a script we wrote in another country.",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Fitness",
        heading: "Walking, not trekking",
        body: "Nothing longer than eleven kilometres in a day and nothing technical. If you can manage a long day on your feet at home you will manage this, altitude allowing.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "scale",
        heading: "Eight travellers per departure",
        body: "Four departures a year, timed to the new moon so the two nights outside are worth the cold. Deposits are refundable up to ninety days out.",
        ctaLabel: "See dates", ctaHref: "#dates",
        scrollHeight: 1000,
      },
    ],
  },
  {
    slug: "aurabeauty",
    name: "AuraBeauty",
    tagline: "Luxury skincare, delivered to your door",
    category: "E-commerce",
    tags: ["Rose", "Luxury", "Retail"],
    style: "wave",
    colors: ["#ec4899", "#f43f5e", "#1a0510"],
    gradient: "from-pink-700 via-rose-800 to-pink-900",
    theme: { fontDisplay: "Playfair Display", fontBody: "Lato", scale: "poster", displayWeight: 700, displayTracking: -0.025, ink: "#fdeef5", muted: "rgba(253,238,245,0.72)", accent: "#b33774", accentText: "#fdc7e2", radius: 18 },
    sections: [
      {
        kind: "statement", layout: "center", reveal: "mask",
        eyebrow: "New collection",
        heading: "Radiance, redefined.",
        ctaLabel: "Shop now", ctaHref: "#section-9",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "stagger",
        eyebrow: "The formula",
        heading: "Nine ingredients, each one doing something",
        body: "Every ingredient is on the front of the box with what it is for beside it. If we cannot say why something is in there, it is not in there.",
        scrollHeight: 1500,
      },
      {
        layout: "left", reveal: "fade",
        eyebrow: "Sourcing",
        heading: "Two growers, both named on the label",
        body: "Rose from Isparta and camellia from Kumamoto, bought on multi-year agreements rather than at spot price. The harvest year is printed on the base of every bottle.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "right", reveal: "stagger",
        eyebrow: "Testing",
        heading: "Patch first, always",
        body: "Every order includes two sachets before you open the bottle. Actives take six weeks to show anything, and a product that promises otherwise is selling you the first three days.",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "fade",
        eyebrow: "The routine",
        heading: "Three steps, not eleven",
        body: "Cleanse, treat, protect. We do not make an essence, a mist or a second serum, because your skin does not need a fourth thing from us to make the first three work.",
        scrollHeight: 1300,
      },
      {
        layout: "right", reveal: "stagger",
        eyebrow: "Refills",
        heading: "The bottle is meant to be kept",
        body: "Glass with an aluminium pump, refilled from a pouch that uses a fifth of the material. The refill costs less than the bottle, which is the only way this works.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "fade",
        eyebrow: "Ordering",
        heading: "Your ritual starts here.",
        body: "Free shipping over sixty pounds and sixty days to change your mind, opened or not. Tell us your skin and we will say honestly which of the three you can skip.",
        ctaLabel: "Shop the collection", ctaHref: "#shop",
        scrollHeight: 1200,
      },
    ],
  },
  {
    slug: "nightrealm",
    name: "NightRealm",
    tagline: "Enter the world beyond the veil",
    category: "Gaming",
    tags: ["Neon", "Gaming", "Loud"],
    style: "particles",
    colors: ["#6d28d9", "#1e1b4b", "#030014"],
    gradient: "from-purple-800 via-indigo-900 to-purple-950",
    theme: { fontDisplay: "Oswald", fontBody: "Roboto", scale: "poster", displayWeight: 700, displayCase: "upper", displayTracking: 0.01, ink: "#eae7fb", muted: "rgba(234,231,251,0.7)", accent: "#6d28d9", accentText: "#e0cefd", radius: 2 },
    sections: [
      {
        kind: "statement", layout: "center", reveal: "mask",
        eyebrow: "Season III — The Veil War",
        heading: "Darkness has a name.",
        ctaLabel: "Play free", ctaHref: "#section-9",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Forge your legend",
        heading: "Every warrior is different.",
        body: "Twelve archetypes, a skill tree that branches rather than tiers, and gear you craft from what you find. Two players at the same level rarely play the same character.",
        scrollHeight: 1500,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "The world",
        heading: "One map, no loading screens",
        body: "The Veil is a single continuous world from the shore to the spire. Where you can see, you can walk, and the weather that ruins your ambush is the same weather everyone else is in.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Season III",
        heading: "The map changes and stays changed",
        body: "Territory taken in a season keeps its scars into the next one. Nothing resets to a clean slate, which makes the middle of a season the interesting part rather than the end.",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Playing together",
        heading: "Groups of four, or nobody",
        body: "Every instance is built for four and scales honestly rather than pretending a solo run is equivalent. Matchmaking will find you three people in under a minute at most hours.",
        scrollHeight: 1300,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "What you pay for",
        heading: "Cosmetics. That is the whole list.",
        body: "No stat boosts, no loot boxes, no energy timer. Everything that affects a fight is earned in the world, because the alternative makes winning meaningless.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "fade",
        eyebrow: "Free to play",
        heading: "The Realm awaits.",
        body: "Cross-platform on PC, PS5, Xbox and mobile, with one account and one save. Download is fourteen gigabytes and the tutorial is skippable.",
        ctaLabel: "Play free", ctaHref: "#play",
        scrollHeight: 1200,
      },
    ],
  },
  {
    slug: "tripvault",
    name: "TripVault",
    tagline: "Every adventure, beautifully organised",
    category: "Mobile App",
    tags: ["Sky", "App", "Friendly"],
    style: "gradient",
    colors: ["#0284c7", "#0891b2", "#020c1a"],
    gradient: "from-sky-700 via-blue-800 to-indigo-900",
    theme: { fontDisplay: "Space Grotesk", fontBody: "Inter", scale: "editorial", displayWeight: 700, ink: "#e8f4fb", muted: "rgba(232,244,251,0.72)", accent: "#026ca3", accentText: "#abddf7", radius: 14 },
    sections: [
      {
        kind: "statement", layout: "center", reveal: "mask",
        eyebrow: "Travel smarter",
        heading: "Your whole trip in one tap.",
        ctaLabel: "Download TripVault", ctaHref: "#section-9",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Trip planning",
        heading: "Built by travellers, not spreadsheets.",
        body: "Say where you are going and TripVault assembles a day-by-day itinerary you can drag around. Move one thing and everything after it moves with the travel time included.",
        scrollHeight: 1500,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Documents",
        heading: "Everything in one place, offline",
        body: "Boarding passes, hotel confirmations, insurance and the visa letter, all readable with no signal. The airport is the worst place to discover a document was in an email.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Together",
        heading: "Share a trip, not a screenshot",
        body: "Everyone on the trip sees the same plan and can add to it. Changes show who made them, so the argument about which train you agreed on has an answer.",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Money",
        heading: "Split as you go, settle once",
        body: "Log a cost in whatever currency you paid it in and TripVault keeps the rate from that day. At the end it tells you the smallest number of transfers that squares everyone up.",
        scrollHeight: 1300,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Your data",
        heading: "Export the whole trip whenever",
        body: "One file with the itinerary, the documents and the costs, readable without the app. Delete your account and it is gone, not archived somewhere for later.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "fade",
        eyebrow: "On iOS and Android",
        heading: "Start your next chapter.",
        body: "Free for solo travellers, with a paid tier for families and groups that adds shared trips and offline maps. No account needed to plan your first one.",
        ctaLabel: "Get it free", ctaHref: "#download",
        scrollHeight: 1200,
      },
    ],
  },
  {
    slug: "greenshift",
    name: "GreenShift",
    tagline: "Climate technology for a liveable planet",
    category: "Startup",
    tags: ["Green", "Climate", "Earnest"],
    style: "wave",
    colors: ["#059669", "#0d9488", "#021a10"],
    gradient: "from-green-700 via-lime-800 to-green-950",
    theme: { fontDisplay: "Archivo", fontBody: "IBM Plex Sans", scale: "editorial", displayWeight: 800, ink: "#e9f7f1", muted: "rgba(233,247,241,0.72)", accent: "#047653", accentText: "#91e7cc", radius: 10 },
    sections: [
      {
        kind: "statement", layout: "center", reveal: "mask",
        eyebrow: "Carbon removal",
        heading: "Decarbonisation at enterprise scale.",
        ctaLabel: "Book a demo", ctaHref: "#section-9",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "stagger",
        eyebrow: "Verified impact",
        heading: "Carbon removal you can actually trust.",
        body: "Every tonne is measured at the point of removal and retired against a serial number you can look up. If a project cannot be measured, we do not sell it.",
        scrollHeight: 1500,
      },
      {
        layout: "left", reveal: "fade",
        eyebrow: "The portfolio",
        heading: "Durable removal, not offsets",
        body: "Mineralisation, biochar and direct air capture, weighted toward the methods that hold carbon for centuries rather than the ones that are cheap this quarter.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "right", reveal: "stagger",
        eyebrow: "Measurement",
        heading: "We publish the uncertainty",
        body: "Every project ships with an error bar, because a removal estimate without one is a marketing number. Where the range is wide we say so and price accordingly.",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "fade",
        eyebrow: "Reporting",
        heading: "Built for the disclosure you have to file",
        body: "Output maps to the frameworks your finance team already reports against, exportable as the evidence pack an auditor asks for rather than a dashboard screenshot.",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "stagger",
        eyebrow: "What this is not",
        heading: "Removal comes after reduction",
        body: "Buying tonnes is the last step, not the first. If your emissions are still rising we will tell you where to spend the money instead, even though we do not get paid for that.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "fade",
        eyebrow: "Getting started",
        heading: "The net-zero future starts now.",
        body: "A demo runs against your own emissions inventory and ends with a portfolio you can take to your board, whether or not you buy anything from us.",
        ctaLabel: "Book a demo", ctaHref: "#demo",
        scrollHeight: 1200,
      },
    ],
  },
  {
    slug: "ember",
    name: "Ember",
    tagline: "Fire-crafted steakhouse, downtown",
    category: "Restaurant",
    tags: ["Fire", "Hospitality", "Warm"],
    style: "particles",
    colors: ["#ea580c", "#b91c1c", "#1a0500"],
    gradient: "from-orange-700 via-red-800 to-orange-950",
    theme: { fontDisplay: "Fraunces", fontBody: "Karla", scale: "poster", displayWeight: 700, displayTracking: -0.02, ink: "#fbeee6", muted: "rgba(251,238,230,0.72)", accent: "#b24309", accentText: "#fcccb4", radius: 6 },
    sections: [
      {
        kind: "statement", layout: "center", reveal: "mask",
        eyebrow: "Now taking reservations",
        heading: "Some things are better burnt.",
        ctaLabel: "Reserve a table", ctaHref: "#section-9",
        scrollHeight: 1400,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "The craft",
        heading: "Fire is the only seasoning we need.",
        body: "A ceramic hearth held at nine hundred degrees puts a crust on a steak that no pan will match. Salt goes on after, because before it draws out the water we are trying to keep.",
        scrollHeight: 1500,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "The beef",
        heading: "Two farms, dry-aged on site",
        body: "Whole sides come in and hang in the room behind the bar for forty days. You can see it from table nine, which is either the best or worst seat depending on you.",
        scrollHeight: 1400,
      },
      { kind: "spacer", scrollHeight: 700 },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "The rest of the menu",
        heading: "Not everything is steak",
        body: "A third of the menu never touches meat and is cooked over the same fire. The roasted allium and the whole celeriac are ordered as often as the ribeye.",
        scrollHeight: 1400,
      },
      {
        layout: "right", reveal: "fade",
        eyebrow: "Wine",
        heading: "Reds that can stand up to smoke",
        body: "Forty bottles, weighted to the ones that survive a charred crust, plus six by the glass. Corkage on a bottle you bring is twenty, and we will decant it properly.",
        scrollHeight: 1300,
      },
      {
        layout: "left", reveal: "stagger",
        eyebrow: "Good to know",
        heading: "It is loud, and it smells of fire",
        body: "An open hearth in a small room does both. Your coat will know you were here. The quietest tables are the two by the window and we will give you one if you ask.",
        scrollHeight: 1300,
      },
      { kind: "spacer", scrollHeight: 600 },
      {
        layout: "center", reveal: "fade",
        eyebrow: "Downtown, Tuesday to Saturday",
        heading: "A meal worth the occasion.",
        body: "Dinner from six, tasting menu Wednesday to Friday, and private dining for up to fourteen. Bookings open four weeks ahead.",
        ctaLabel: "Reserve a table", ctaHref: "#reserve",
        scrollHeight: 1200,
      },
    ],
  },
];
