"use client";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ArrowRight, Sparkles, Zap, Download, Play } from "lucide-react";

const TEMPLATES = [
  { title: "SaaS Hero", description: "Floating UI with depth", color: "from-violet-600 to-purple-900" },
  { title: "Product Launch", description: "Cinematic reveal", color: "from-blue-600 to-indigo-900" },
  { title: "Agency Portfolio", description: "Bold & minimal", color: "from-rose-600 to-pink-900" },
  { title: "App Showcase", description: "Device mockup scroll", color: "from-emerald-600 to-teal-900" },
  { title: "E-commerce", description: "Product 360 spin", color: "from-amber-600 to-orange-900" },
  { title: "Restaurant", description: "Food & atmosphere", color: "from-red-600 to-rose-900" },
];

const FEATURES = [
  { icon: Sparkles, title: "AI Video Generation", desc: "Describe your vision and get a cinematic 8-second video generated by AI" },
  { icon: Zap, title: "Auto Frame Extraction", desc: "400+ frames extracted automatically for buttery-smooth scroll animation" },
  { icon: Play, title: "Scroll Engine", desc: "Native browser scroll — no WebGL, no Three.js, works on every device" },
  { icon: Download, title: "One-Click Export", desc: "Production-ready HTML/CSS/JS bundle, deployable anywhere in seconds" },
];

export default function Home() {
  return (
    <main className="min-h-screen bg-background text-foreground overflow-x-hidden">
      <nav className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-8 py-4 border-b border-white/5 bg-background/80 backdrop-blur-xl">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg bg-primary flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-white" />
          </div>
          <span className="font-semibold text-lg tracking-tight">ScrollCraft</span>
        </div>
        <div className="flex items-center gap-4">
          <Link href="#templates" className="text-sm text-muted-foreground hover:text-foreground transition-colors">Templates</Link>
          <Link href="#features" className="text-sm text-muted-foreground hover:text-foreground transition-colors">Features</Link>
          <Link href="/create">
            <Button size="sm" className="bg-primary hover:bg-primary/90 text-white">Start Building</Button>
          </Link>
        </div>
      </nav>

      <section className="relative flex flex-col items-center justify-center min-h-screen text-center px-6 pt-20">
        <div className="absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] rounded-full bg-primary/10 blur-[120px] pointer-events-none" />
        <div className="absolute top-2/3 left-1/4 w-[300px] h-[300px] rounded-full bg-blue-500/8 blur-[100px] pointer-events-none" />

        <Badge variant="outline" className="mb-6 border-primary/40 text-primary bg-primary/10 px-4 py-1.5">
          <Sparkles className="w-3 h-3 mr-1.5" /> AI-Powered · No Code · 3D Scroll
        </Badge>

        <h1 className="text-6xl md:text-8xl font-black tracking-tighter mb-6 leading-none">
          Build cinematic<br />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-violet-400 via-purple-400 to-indigo-400">
            scroll websites
          </span><br />
          in minutes
        </h1>

        <p className="text-xl text-muted-foreground max-w-2xl mb-10 leading-relaxed">
          Describe a visual atmosphere. Our AI generates a cinematic video, extracts 400+ frames,
          and wires it all up as a silky 3D parallax scroll experience — exported as pure HTML.
        </p>

        <div className="flex flex-col sm:flex-row items-center gap-4">
          <Link href="/create">
            <Button size="lg" className="bg-primary hover:bg-primary/90 text-white px-8 py-6 text-base font-semibold shadow-lg shadow-primary/25">
              Create your site <ArrowRight className="ml-2 w-5 h-5" />
            </Button>
          </Link>
          <Link href="#templates">
            <Button size="lg" variant="outline" className="border-white/10 hover:bg-white/5 px-8 py-6 text-base">
              Browse templates
            </Button>
          </Link>
        </div>

        <div className="relative mt-20 w-full max-w-4xl mx-auto rounded-2xl overflow-hidden border border-white/10 shadow-2xl shadow-black/50">
          <div className="aspect-video bg-gradient-to-br from-violet-900/40 to-black flex items-center justify-center">
            <div className="flex flex-col items-center gap-4">
              <div className="w-16 h-16 rounded-full border-2 border-primary/50 flex items-center justify-center animate-pulse">
                <Play className="w-6 h-6 text-primary ml-1" />
              </div>
              <p className="text-muted-foreground text-sm">Scroll to experience 3D parallax</p>
            </div>
          </div>
          <div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-transparent pointer-events-none" />
        </div>
      </section>

      <section id="features" className="py-32 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <Badge variant="outline" className="mb-4 border-white/10">How it works</Badge>
            <h2 className="text-4xl md:text-5xl font-black tracking-tighter">
              From prompt to production<br />
              <span className="text-muted-foreground">in 4 steps</span>
            </h2>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {FEATURES.map((f, i) => (
              <div key={f.title} className="relative p-6 rounded-2xl border border-white/8 bg-card hover:border-primary/30 transition-colors group">
                <div className="absolute top-4 right-4 text-4xl font-black text-white/5 group-hover:text-primary/10 transition-colors">{i + 1}</div>
                <div className="w-10 h-10 rounded-xl bg-primary/15 flex items-center justify-center mb-4">
                  <f.icon className="w-5 h-5 text-primary" />
                </div>
                <h3 className="font-semibold mb-2">{f.title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section id="templates" className="py-32 px-6 border-t border-white/5">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <Badge variant="outline" className="mb-4 border-white/10">Ready to use</Badge>
            <h2 className="text-4xl md:text-5xl font-black tracking-tighter">Start from a template</h2>
            <p className="text-muted-foreground mt-4 max-w-lg mx-auto">
              Production-tested starters for every industry. Customize with AI or edit directly.
            </p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {TEMPLATES.map((t) => (
              <Link key={t.title} href={`/create?template=${encodeURIComponent(t.title)}`}>
                <div className="group relative rounded-2xl border border-white/8 overflow-hidden hover:border-primary/40 transition-all hover:-translate-y-1 cursor-pointer">
                  <div className={`aspect-video bg-gradient-to-br ${t.color} flex items-end p-5`}>
                    <div>
                      <p className="font-semibold text-white">{t.title}</p>
                      <p className="text-sm text-white/60">{t.description}</p>
                    </div>
                  </div>
                  <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity bg-black/40">
                    <Button size="sm" className="bg-primary text-white">Use template <ArrowRight className="ml-1 w-3 h-3" /></Button>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      <section className="py-32 px-6 text-center border-t border-white/5">
        <div className="relative max-w-3xl mx-auto">
          <div className="absolute inset-0 rounded-3xl bg-primary/5 blur-3xl" />
          <div className="relative">
            <h2 className="text-5xl md:text-6xl font-black tracking-tighter mb-6">Ready to build?</h2>
            <p className="text-xl text-muted-foreground mb-10">No design skills. No code. Just describe what you see in your head.</p>
            <Link href="/create">
              <Button size="lg" className="bg-primary hover:bg-primary/90 text-white px-10 py-7 text-lg font-semibold shadow-xl shadow-primary/30">
                Start for free <ArrowRight className="ml-2 w-5 h-5" />
              </Button>
            </Link>
          </div>
        </div>
      </section>

      <footer className="py-8 px-6 border-t border-white/5 text-center text-sm text-muted-foreground">
        <div className="flex items-center justify-center gap-2">
          <div className="w-5 h-5 rounded bg-primary/20 flex items-center justify-center">
            <Sparkles className="w-3 h-3 text-primary" />
          </div>
          ScrollCraft — Built with Next.js & AI
        </div>
      </footer>
    </main>
  );
}
